CREATE TABLE USUARIO (
  ID_USUARIO int NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(50) NOT NULL,
  PATERNO varchar(50) NOT NULL,
  MATERNO varchar(50) NOT NULL,
  ACTIVO int DEFAULT 1,
  PRIMARY KEY (ID_USUARIO)
) ;

CREATE TABLE CAT_STATUS (
  ID_STATUS int NOT NULL AUTO_INCREMENT,
  DESCRIPCION varchar(45) DEFAULT NULL,
  ACTIVO int DEFAULT 1,
  CREACION date DEFAULT CURDATE(),
  PRIMARY KEY (ID_STATUS)
) ;

-- -- NOTA: El campo ID_USUARIO, es el propietario de la tarea.
CREATE TABLE TAREA (
  ID_TAREA int NOT NULL AUTO_INCREMENT,
  TITULO varchar(100) DEFAULT NULL,
  DESCRIPCION varchar(300) DEFAULT NULL,
  ID_STATUS int DEFAULT 1,
  ID_USUARIO int NOT NULL, 
  CREACION date DEFAULT CURDATE(),
  FINALIZACION date DEFAULT NULL,
  PRIMARY KEY (ID_TAREA),
  CONSTRAINT fk_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
  CONSTRAINT fk_CAT_STATUS FOREIGN KEY (ID_STATUS) REFERENCES CAT_STATUS (ID_STATUS)
) ;

-- Listado de ejemplos...
INSERT INTO USUARIO (NOMBRE, PATERNO, MATERNO)
VALUES ('Nombre','Apellido Paterno','Apellido Materno');

INSERT INTO TAREA (ID_USUARIO, TITULO, DESCRIPCION)
VALUES (0,"Titulo tarea.","Cuerpo tarea.");

SELECT 
  TAREA.TITULO AS "TASK_TITULO",
  TAREA.DESCRIPCION AS "TASK_DESCRIPCION",
  TAREA.CREACION AS "TASK_FECHA_CREACION",
  CAT_STATUS.DESCRIPCION AS "TASK_STATUS"
FROM TAREA
INNER JOIN USUARIO
ON TAREA.ID_USUARIO = USUARIO.ID_USUARIO
INNER JOIN CAT_STATUS
ON TAREA.ID_STATUS = CAT_STATUS.ID_STATUS
WHERE USUARIO.ID_USUARIO = 1 AND TAREA.ID_STATUS = 1;